# Numpy基础

## 一、数组——更适合数据分析的列表

In [2]:
import numpy as np

### 1. 创建数组

#### （1）创建一维数组

In [3]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

#### （2）创建二维数组

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

注意：数组与列表不同，需要数组中的元素都为同一类型；  
传入数组元素不同，array方法会强制将其转换成同一类型。

In [5]:
arr3 = np.array(["hello", 3.14, True])
arr3

array(['hello', '3.14', 'True'], dtype='<U32')

### 2. 数组对象的属性

#### (1)返回数组的维度：

In [12]:
print(arr1.ndim)
print(arr2.ndim)

1
2


#### (2)返回数组的维度及个数

In [13]:
print(arr1.shape)
print(arr2.shape)

(3,)
(2, 3)


#### (3)返回数组中元素总个数

In [14]:
print(arr1.size)
print(arr2.size)

3
6


#### (4)返回数组中元素的类型

In [15]:
print(arr1.dtype)
print(arr2.dtype)

int64
int64


### 3. 其他创建数组方法

#### （1）创造元素全部为0（或者1）的数组

In [9]:
zeros = np.zeros(3)
ones = np.ones(5)
print(zeros)
print(ones)

[0. 0. 0.]
[1. 1. 1. 1. 1.]


注：此数组元素后面有小数点，说明创造的都是浮点数

#### （2）创造元素为数组序列的数组

In [10]:
np.arange(5,10,2)

array([5, 7, 9])

注：（x, y, z）中x为起始数，y为终止数，z为步长  
终止数不会包括在数组里

## 二、数组的整理与运算

### 1.数组的连接、排序、索引与切片

#### （1）数组连接

In [11]:
arr4 = np.array([1,3,5,7,9])
arr5 = np.array([2,4])
np.concatenate([arr4,arr5])

array([1, 3, 5, 7, 9, 2, 4])

#### （2）数组排序

##### sort函数

In [12]:
arr6 = np.array([5,17,3,26,31])
print(np.sort(arr6))
print(arr6)

[ 3  5 17 26 31]
[ 5 17  3 26 31]


##### sort方法

In [13]:
arr6 = np.array([5,17,3,26,31])
print(arr6.sort())
print(arr6)

None
[ 3  5 17 26 31]


注：运用sort对数组进行排序，会返回一个排序好的数组，不改变原来的数组；  
对数组进行sort方法会把原来的数组排序好，什么都不返回。

#### （3）数组索引与切片

In [14]:
arr6[0]

3

In [15]:
arr6[-2]

26

In [16]:
arr6[1:3]

array([ 5, 17])

### 2.数组的运算

#### （1）加减乘除运算

In [17]:
arr7 = np.array([6,7,8,9,10])
arr8 = np.ones(5)
arr7 + arr8

array([ 7.,  8.,  9., 10., 11.])

In [18]:
arr7 - arr8

array([5., 6., 7., 8., 9.])

In [19]:
arr7 * arr8

array([ 6.,  7.,  8.,  9., 10.])

In [20]:
arr7 / arr8

array([ 6.,  7.,  8.,  9., 10.])

In [21]:
3 * arr7

array([18, 21, 24, 27, 30])

In [22]:
arr7 *3

array([18, 21, 24, 27, 30])

#### （2）统计运算

In [23]:
arr7.max()

10

In [24]:
arr7.min()

6

In [25]:
arr7.sum()

40

In [26]:
arr7.mean()

8.0

#### （3）根据条件筛选数组元素

In [27]:
arr9 = np.array([-22,3,65,9,11,7])

In [28]:
arr9[arr9 > 6]

array([65,  9, 11,  7])

#### （4）逻辑运算

与（and）

In [29]:
arr9[(arr9 > 6)&(arr9 < 10)]

array([9, 7])

或（or）

In [30]:
arr9[(arr9 < 6)|(arr9 > 10)]

array([-22,   3,  65,  11])

非（not）

In [31]:
arr9[~(arr9 > 6)]

array([-22,   3])